### PR TITLE
Update to 3.1

### PR DESCRIPTION
**Pull request by gmaggess**
Update to Knockout 3.1.0

### CODE REVIEW

**Comment by nick1one** [comment]
Yeah! Make new buid.

**Comment by cdekok** [comment]
Yes plz merge

**Comment by juuxstar** [comment]
There's already an outstanding issue and pull request for this.  Please close and +1 the other issue.  It's really frustrating that whoever started this isn't updating this project .

**Comment by chadly** [comment]
Knockout now provides its own built files for bower negating the need for this repository. See knockout/knockout#1039. Remove the reference to `knockout.js` in your `bower.json` and `bower install knockout`

**Comment by jhnlsn** [comment]
merged in #13 instead of this one

**Pull request closed without merging**
