### PR TITLE
Update Knockout to v3.1.0

### PR DESCRIPTION
**Pull request by msteward**
Propose to update Knockout to latest v3.1.0

### CODE REVIEW

**Comment by julienaubert** [comment]
+1

**Comment by BardurArantsson** [comment]
+1

**Comment by chadly** [comment]
:+1:

**Comment by mdarens** [comment]
:+1:

**Comment by juuxstar** [comment]
+1

**Comment by aadamyan** [comment]
:+1:

**Comment by mokkabonna** [comment]
+1 @johnymonster

**Comment by leszekhanusz** [comment]
:+1:

**Comment by chadly** [comment]
Knockout now provides its own built files for bower negating the need for this repository. See knockout/knockout#1039. Remove the reference to `knockout.js` in your `bower.json` and `bower install knockout`

**Pull request merged**
